### ISSUE TITLE
Better invariant check

### ISSUE THREAD

**Issue by ladvoc** [ladvoc/BijectiveDictionary#12]
The invariant check as [defined here](https://github.com/ladvoc/BijectiveDictionary/blob/175cec4451cc7365709be1ce9c0bfa12532217bf/Sources/BijectiveDictionary/BijectiveDictionary%2BInvariant.swift#L12) should check to make sure that `_ltr` and `_rtl` contain the same left-right pairs (order may vary); current implementation just checks counts. This has no overhead unless compiled with `DEBUG`.

**Comment by DandyLyons** [comment]
If order doesn’t matter I think we should be able to just do _ltr == _rtl
